# Tutorial 1: Introduction to Python

### Developed by Cristiana Tisca with examples taken from the Wellcome Centre for Integrative Neuroimaging PyTreat course: https://git.fmrib.ox.ac.uk/fsl/win-pytreat/.

This tutorial aims to give you an overview of the Python Programming language.

It assumes that you have the following installed on your computer:
- Python version 3.0.0 or up

And the following python libraries:
- jupyter 
- numpy

All of the code can be run on your own machines. All of the following code blocks can be run by clicking **SHIFT+ENTER**. You can also edit each individual bloc. 

You can get help on any Python object, function, or method by putting a `?`
before or after the thing you want help on:

In [ ]:
a = 'hello!'
?a.upper

In [ ]:
# Put the cursor after the dot, and press the TAB key...
a.

# Variables and basic types

## Integer and floating point scalars

In [ ]:
a = 7
b = 1 / 3
c = a + b
print('a:     ', a)
print('b:     ', b)
print('c:     ', c)
print(f'b:     {b:0.4f}')
print('a + b: ', a + b)

## Strings 

In [ ]:
a = 'Hello'
b = "Kitty"
c = """
Magic
multi-line
strings!
"""

print(a, b)
print(a + b)
print(f'{a}, {b}!')
print(c)

### Methods for strings

Have a look at the following examples of methods to manipulate strings. Make sure you understand what each 
method does. If anything is unclear, please ask.

Example 1:

In [1]:
s = 'This is a Test String'
print(s.upper())
print(s.lower())

THIS IS A TEST STRING
this is a test string


Example 2:

In [ ]:
s = 'This is a Test String'
s2 = s.replace('Test', 'Better')
print(s2)

Example 3:

In [ ]:
s2 = '   A very    spacy   string       '
print('*' + s2 + '*')
print('*' + s2.strip() + '*')

Example 4:

In [ ]:
print(s.split())
print(s2.split())

Example 5:

In [ ]:
data = ' 1,2,3,4,5,6,7 '
print(f'Original:              {data}')
print('Strip, split, and join:', ' '.join(data.strip().split(',')))

## Lists and tuples


Tuples are defined using round brackets and lists are defined using square
brackets. 

In [ ]:
t = (3, 7.6, 'str')
l = [1, 'mj', -5.4]
print(t)
print(l)

t2 = (t, l)
l2 = [t, l]
print('t2 is: ', t2)
print('l3 is: ', l2)
print(len(t2))
print(len(l2))

The key difference between lists and tuples is that tuples are *immutable*
(once created, they cannot be changed), whereas lists are *mutable*:

In [ ]:
a = [10, 20, 30]
a[2] = 999
print(a)

Square brackets are used to index tuples, lists, strings, dictionaries, etc.
For example:

In [ ]:
d = [10, 20, 30]
print(d[1])

**Important note**: Python uses zero-based indexing, indices start from zero

In [ ]:
a = [10, 20, 30, 40, 50, 60]
print(a[0])
print(a[2])

A range of values for the indices can be specified to extract values from a
list or tuple using the `:` character.  For example:

In [ ]:
print(a[0:3])

When slicing a list or tuple, you can leave the start and end values out -
when you do this, Python will assume that you want to start slicing from the
beginning or the end of the list.  For example:

In [ ]:
print(a[:3])
print(a[1:])
print(a[:])
print(a[:-1])

You can also change the step size.

In [ ]:
print(a[0:4:2])
print(a[::2])
print(a[::-1])

Some methods are available on `list` objects for adding and removing items:

In [ ]:
print(d)
d.append(40)
print(d)
d.extend([50, 60])
print(d)
d = d + [70, 80]
print(d)
d.remove(20)
print(d)
d.pop(0)
print(d)

What will `d.append([50,60])` do, and how is it different from
`d.extend([50,60])`?

In [ ]:
d.append([50, 60])
print(d)

## Dictionaries


Dictionaries (or *dicts*) can be used to store key-value pairs. Almost
anything can used as a key, and anything can be stored as a value; it is
common to use strings as keys:

In [ ]:
e = {'a' : 10, 'b': 20}
print(len(e))
print(e.keys())
print(e.values())
print(e['a'])

Like lists (and unlike tuples), dicts are mutable, and have a number of
methods for manipulating them:

In [ ]:
e['c'] = 30
e.pop('a')
e.update({'a' : 100, 'd' : 400})
print(e)
e.clear()
print(e)

### Mutability

Python variables can refer to values which are either mutable, or
immutable. Examples of immutable values are strings, tuples, and integer and
floating point scalars. Examples of mutable values are lists, dicts, and most
user-defined types.


When you pass an immutable value around (e.g. into a function, or to another
variable), it works the same as if you were to copy the value and pass in the
copy - the original value is not changed:

In [ ]:
a = 'abcde'
b = a
b = b.upper()
print('a:', a)
print('b:', b)

In contrast, when you pass a mutable value around, you are passing a
*reference* to that value - there is only ever one value in existence, but
multiple variables refer to it. You can manipulate the value through any of
the variables that refer to it:

In [ ]:
a = [1, 2, 3, 4, 5]
b = a

a[3] = 999
b.append(6)

print('a', a)
print('b', b)

## Flow control
Python also has a boolean type which can be either `True` or `False`. Most
Python types can be implicitly converted into booleans when used in a
conditional expression.


Relevant boolean and comparison operators include: `not`, `and`, `or`, `==`
and `!=`


For example:

In [ ]:
a = True
b = False
print('Not a is:', not a)
print('a or b is:', a or b)
print('a and b is:', a and b)
print('Not 1 is:', not 1)
print('Not 0 is:', not 0)
print('Not {} is:', not {})
print('{}==0 is:', {}==0)

 There is also the `in` test for strings, lists, etc:

In [ ]:
print('the' in 'a number of words')
print('of' in 'a number of words')
print(3 in [1, 2, 3, 4])

# Functions and control structures
### If statement
When you need to execute a block of code only if a particular condition is true, you can use the `if` statement. If the condition evaluates to false, the block of code is not executed.
Example:

In [ ]:
temperature = 15

if temperature <= 25:
    print("Bummer! We can't go swimming!")

  

### If-else statement
The `if-else` statement allows you to execute one block of code if the condition is true, and a different block if the condition is false.

In [ ]:
score = 15

if score <= 25:
    print("Bummer! We can't go swimming!")
else:
    print("Yay! Let's go for a swim!")

  

### If-else-elif statement

The `if-elif-else` statement is used when you have multiple conditions to check. It allows you to test multiple conditions and execute the corresponding block of code for the first true condition encountered.

In [ ]:
score = 82

if score >= 90:
    print("Excellent! You got an A.")
elif score >= 80:
    print("Good job! You got a B.")
elif score >= 70:
    print("Not bad! You got a C.")
else:
    print("You need to improve. You got an F.")

  

### Nested If Statements

In [ ]:
name = "Alice"
score = 78

if name == "Alice":
    if score >= 80:
        print("Great job, Alice! You got an A.")
    else:
        print("Good effort, Alice! Keep it up.")
else:
    print("You're doing well, but this message is for Alice.")

### For loop
In Python, the `for` loop provides a concise syntax to let us iterate over existing iterables. We can iterate over `student_names` list like so:



In [ ]:
student_names = ["Alice", "Bob", "Charlie", "David"]

for name in student_names:
    print("Student:", name)

### While loop
If you want to execute a piece of code as long as a condition is true, you can use a `while` loop.

In [ ]:
# Using a while loop with an existing iterable

student_names = ["Alice", "Bob", "Charlie", "David"]
index = 0

while index < len(student_names):
    print("Student:", student_names[index])
    index += 1

### Loop Control Statements

 

`break` exits the loop prematurely, and `continue` skips the rest of the current iteration and moves to the next one.

In [ ]:
student_names = ["Alice", "Bob", "Charlie", "David"]

for name in student_names:
    if name == "Charlie":
        break
    print(name)

### A few more examples: 
We can use boolean values in `if`-`else` conditional expressions:

In [ ]:
a = [1, 2, 3, 4]
val = 3
if val in a:
    print(f'Found {val}!')
else:
    print(f'{val} not found :(')

Note that the indentation in the `if`-`else` statement is **crucial**.
**All** python control blocks are delineated purely by indentation. We
recommend using **four spaces** and no tabs, as this is a standard practice
and will help a lot when collaborating with others.


You can use the `for` statement to loop over elements in a list:

In [ ]:
d = [10, 20, 30]
for x in d:
    print(x)

You can also loop over the key-value pairs in a dict:

In [ ]:
a = {'a' : 10, 'b' : 20, 'c' : 30}
print('a.keys()')
for key in a.keys():
    print(key, a[key])
print('a.values()')
for val in a.values():
    print(val)
print('a.items()')
for key, val in a.items():
    print(key, val)

There are some handy built-in functions that you can use with `for` loops:

In [ ]:
d = [10, 20, 30]
print('Using the range function')
for i in range(len(d)):
    print(f'element at position {i}: {d[i]}')

print('Using the enumerate function')
for i, elem in enumerate(d):
    print(f'element at position {i}: {elem}')

# List comprehensions
Python has a really neat way to create lists (and dicts), called
*comprehensions*. Let's say we have some strings, and we want to count the
number of characters in each of them:

In [ ]:
strings = ['hello', 'howdy', 'hi', 'hey']
nchars = [len(s) for s in strings]
for s, c in zip(strings, nchars):
    print(f'{s}: {c}')

> The `zip` function "zips" two or more sequences, so you can loop over them
> together.


Or we could store the character counts in a dict:

In [ ]:
nchars = { s : len(s) for s in strings }

for s, c in nchars.items():
    print(f'{s}: {c}')

## Copying and references
In python there are immutable types (e.g. numbers) and mutable types (e.g. lists). The main thing to know is that assignment can sometimes create separate copies and sometimes create references (as in C++). In general, the more complicated types are assigned via references. For example:

In [ ]:
a = 7
b = a
a = 2348
print(b)

As oposed to:

In [ ]:
a = [7]
b = a
a[0] = 8888
print(b)

But if an operation is performed then a copy might be made:

In [ ]:
a = [7]
b = a * 2
a[0] = 8888
print(b)

If an explicit copy is necessary then this can be made using the `list()` constructor:

In [ ]:
a = [7]
b = list(a)
a[0] = 8888
print(b)

There is a constructor for each type and this can be useful for converting between types:

In [ ]:
xt = (2, 5, 7)
xl = list(xt)
print(xt)
print(xl)

# Reading and writing text files 
The syntax to open a file in python is

> ```
> with open(<filename>, <mode>) as <file_object>:
>     <block of code>
> ```

* `<filename>` is a string with the name of the file
* `<mode>` is one of `'r'` (for read-only access), `'w'` (for writing a file,
  this wipes out any existing content), `'a'` (for appending to an existing
  file).
* `<file_object>` is a variable name which will be used within the
  `<block of code>` to access the opened file.
    
You can write files like this:


In [ ]:
with open('new_file.txt', 'w') as f:
    f.write('This is my first line\n')
    f.writelines(['Second line\n', 'and the third\n'])

And read them like this:

In [ ]:
with open('new_file.txt', 'r') as f:
    print(f.read())

## Functions 

Functions are a set of actions that we group together, and give a name to. You have already used a number of functions from the core Python language, such as string.title() and list.sort(). We can define our own functions, which allows us to "teach" Python new behavior.

The general syntax for functions is:


In [ ]:
# Let's define a function.
def function_name(argument_1, argument_2):
	# Do whatever we want this function to do,
	#  using argument_1 and argument_2

# Use function_name to call the function.
function_name(value_1, value_2)

This code will not run, but it shows how functions are used in general.

Defining a function
- Give the keyword `def`, which tells Python that you are about to define a function.
- Give your function a name. A variable name tells you what kind of value the variable contains; a function name should tell you what the function does.
- Give names for each value the function needs in order to do its work. These are basically variable names, but they are only used in the function.They can be different names than what you use in the rest of your program. These are called the function's arguments.
- Make sure the function definition line ends with a colon.
- Inside the function, write whatever code you need to make the function do its work.


Using your function
- To call your function, write its name followed by parentheses.
- Inside the parentheses, give the values you want the function to work with.

Example:

In [ ]:
def myfunc(x, y, z=0):
    r2 = x*x + y*y + z*z
    r = r2**0.5
    return r,  r2

rad = myfunc(10, 20)
print(rad)
rad, dummy = myfunc(10, 20, 30)
print(rad)
rad, _ = myfunc(10,20,30)
print(rad)

# Numpy
Python's
numerical computing library. Numpy adds a new data type to the Python
language - the `array` (more specifically, the `ndarray`). A Numpy `array`
is a N-dimensional array of homogeneously-typed numerical data.


Pretty much every scientific computing library in Python is built on top of
Numpy - whenever you want to access some data, you will be accessing it in the
form of a Numpy array. So it is worth getting to know the basics.

In [6]:
import numpy as np

data = np.array([10, 8, 12, 14, 7, 6, 11])

xyz_coords = np.array([[-11.4,   1.0,  22.6],
                       [ 22.7, -32.8,  19.1],
                       [ 62.8, -18.2, -34.5]])
print('data:            ', data)
print('xyz_coords:      ', xyz_coords)
print('data.shape:      ', data.shape)
print('xyz_coords.shape:', xyz_coords.shape)

data:             [10  8 12 14  7  6 11]
xyz_coords:       [[-11.4   1.   22.6]
 [ 22.7 -32.8  19.1]
 [ 62.8 -18.2 -34.5]]
data.shape:       (7,)
xyz_coords.shape: (3, 3)


### Creating arrays

In [7]:
print('np.zeros gives us zeros:                       ', np.zeros(5))
print('np.ones gives us ones:                         ', np.ones(5))
print('np.arange gives us a range:                    ', np.arange(5))
print('np.linspace gives us N linearly spaced numbers:', np.linspace(0, 1, 5))
print('np.random.random gives us random numbers [0-1]:', np.random.random(5))
print('np.random.randint gives us random integers:    ', np.random.randint(1, 10, 5))
print('np.eye gives us an identity matrix:')
print(np.eye(4))
print('np.diag gives us a diagonal matrix:')
print(np.diag([1, 2, 3, 4]))

np.zeros gives us zeros:                        [0. 0. 0. 0. 0.]
np.ones gives us ones:                          [1. 1. 1. 1. 1.]
np.arange gives us a range:                     [0 1 2 3 4]
np.linspace gives us N linearly spaced numbers: [0.   0.25 0.5  0.75 1.  ]
np.random.random gives us random numbers [0-1]: [0.57036129 0.60603892 0.63408493 0.59514676 0.90849115]
np.random.randint gives us random integers:     [3 8 1 2 6]
np.eye gives us an identity matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
np.diag gives us a diagonal matrix:
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


The `zeros` and `ones` functions can also be used to generate N-dimensional
arrays:

In [8]:
z = np.zeros((3, 4))
o = np.ones((2, 10))
print(z)
print(o)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### Array properties

In [9]:
z = np.zeros((2, 3, 4))
print(z)
print('Shape:                     ', z.shape)
print('Number of dimensions:      ', z.ndim)
print('Number of elements:        ', z.size)
print('Data type:                 ', z.dtype)
print('Number of bytes:           ', z.nbytes)
print('Length of first dimension: ', len(z))

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
Shape:                      (2, 3, 4)
Number of dimensions:       3
Number of elements:         24
Data type:                  float64
Number of bytes:            192
Length of first dimension:  2


### Descriptive statistics

In [ ]:
a = np.random.random(10)
print('a: ', a)
print('min:          ', a.min())
print('max:          ', a.max())
print('index of min: ', a.argmin())  # remember that in Python, list indices
print('index of max: ', a.argmax())  # start from zero - Numpy is the same!
print('mean:         ', a.mean())
print('variance:     ', a.var())
print('stddev:       ', a.std())
print('sum:          ', a.sum())
print('prod:         ', a.prod())

### Mathematical operations

In [ ]:
a = np.arange(1, 10).reshape((3, 3))
print('a:')
print(a)
print('a + 2:')
print( a + 2)
print('a * 3:')
print( a * 3)
print('a % 2:')
print( a % 2)

### Matrix multiplications

In [ ]:
a = np.arange(1, 5).reshape((2, 2))
b = a.T

print('a:')
print(a)
print('b:')
print(b)

print('a @ b')
print(a @ b)

print('a.dot(b)')
print(a.dot(b))

print('b.dot(a)')
print(b.dot(a))

### Indexing multi-dimensional arrays


Multi-dimensional array indexing works in much the same way as one-dimensional
indexing but with more dimensions. Use commas within the square
brackets to separate the slices for each dimension:

In [10]:
a = np.arange(25).reshape((5, 5))
print('a:')
print(a)
print(' First row:     ', a[  0, :])
print(' Last row:      ', a[ -1, :])
print(' second column: ', a[  :, 1])
print(' Centre:')
print(a[1:4, 1:4])

a:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
 First row:      [0 1 2 3 4]
 Last row:       [20 21 22 23 24]
 second column:  [ 1  6 11 16 21]
 Centre:
[[ 6  7  8]
 [11 12 13]
 [16 17 18]]


## File management

In this section we will introduce you to file management - how do we find and
manage files, directories and paths in Python?

## Managing files and directories


The `os` module contains functions for querying and changing the current
working directory, moving and removing individual files, and for listing,
creating, removing, and traversing directories.

In [11]:
import os
import os.path as op

### Querying and changing the current directory


You can query and change the current directory with the `os.getcwd` and
`os.chdir` functions.



In [12]:
cwd = os.getcwd()
print(f'Current directory: {cwd}')

os.chdir(op.expanduser('~'))
print(f'Changed to: {os.getcwd()}')

os.chdir(cwd)
print(f'Changed back to: {cwd}')

Current directory: C:\Users\Titus\PycharmProjects\oxfordml
Changed to: C:\Users\Titus
Changed back to: C:\Users\Titus\PycharmProjects\oxfordml



Use the `os.listdir` function to get a directory listing (a.k.a. the Unix `ls`
command):

In [14]:
cwd = os.getcwd()
listing = os.listdir(cwd)
print(f'Directory listing: {cwd}')
print('\n'.join(listing))
print()

datadir = 'raw_mri_data'
listing = os.listdir(datadir)
print(f'Directory listing: {datadir}')
print('\n'.join(listing))

Directory listing: C:\Users\Titus\PycharmProjects\oxfordml
.idea
.ipynb_checkpoints
.venv
pp10.py
Tutorial 1 - Introduction to Python.ipynb



FileNotFoundError: [WinError 3] The system cannot find the path specified: 'raw_mri_data'

You can, not surprisingly, use the `os.mkdir` function to make a
directory. The `os.makedirs` function is also handy - it is equivalent to
`mkdir -p` in Unix:

In [15]:
print(os.listdir('.'))
os.mkdir('onedir')
os.makedirs('a/big/tree/of/directories')
print(os.listdir('.'))

['.idea', '.ipynb_checkpoints', '.venv', 'pp10.py', 'Tutorial 1 - Introduction to Python.ipynb']
['.idea', '.ipynb_checkpoints', '.venv', 'a', 'onedir', 'pp10.py', 'Tutorial 1 - Introduction to Python.ipynb']
